# Generated by Django 5.1.6 on 2025-03-01 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(blank=True, max_length=10, unique=True)),
                ('product_type', models.CharField(choices=[('Private Car', 'Private Car'), ('PCV', 'PCV'), ('GCV', 'GCV'), ('Misc-D', 'Misc-D')], max_length=50)),
                ('business_type', models.CharField(choices=[('New Business', 'New Business'), ('Renewal', 'Renewal'), ('Rollover', 'Rollover'), ('Break-In', 'Break-In')], max_length=50)),
                ('coverage_type', models.CharField(choices=[('Comprehensive', 'Comprehensive'), ('Third Party', 'Third Party'), ('SAOD', 'SAOD')], max_length=50)),
                ('make_model_variant', models.CharField(max_length=200)),
                ('registration_date', models.DateField()),
                ('add_ons', models.CharField(blank=True, max_length=200)),
                ('preferred_insurer', models.CharField(choices=[('ICICI', 'ICICI'), ('HDFC', 'HDFC'), ('Future', 'Future'), ('Digit', 'Digit'), ('Others', 'Others')], max_length=50)),
                ('preferred_idv', models.CharField(blank=True, max_length=100)),
                ('additional_requirements', models.TextField(blank=True)),
                ('document1', models.FileField(blank=True, upload_to='quotation_docs/')),
                ('document2', models.FileField(blank=True, upload_to='quotation_docs/')),
                ('document3', models.FileField(blank=True, upload_to='quotation_docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Assigned', 'Assigned'), ('Resolved', 'Resolved')], default='Open', max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
