# Generated by Django 5.1.6 on 2025-03-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationrequest',
            name='registration_number',
            field=models.CharField(default='N/A', max_length=20),
        ),
    ]
