# Generated by Django 5.1.6 on 2025-03-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_quotationrequest_registration_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationrequest',
            name='registration_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
