# Generated by Django 5.1.6 on 2025-03-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_quotationrequest_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationrequest',
            name='resolution',
            field=models.TextField(blank=True, null=True),
        ),
    ]
