# Generated by Django 5.1.6 on 2025-03-03 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_insurer_quotationrequest_on_field_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='quotationrequest',
            name='on_field',
        ),
        migrations.RemoveField(
            model_name='quotationrequest',
            name='add_ons',
        ),
        migrations.AlterField(
            model_name='quotationrequest',
            name='preferred_insurer',
            field=models.ManyToManyField(blank=True, related_name='quotation_requests', to='tickets.insurer'),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='add_ons',
            field=models.ManyToManyField(blank=True, related_name='quotation_requests', to='tickets.addon'),
        ),
    ]
