# Generated by Django 5.1.6 on 2025-03-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_addon_remove_quotationrequest_on_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationrequest',
            name='claim_status',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True, verbose_name='Previous Year Claim Status'),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='ncb',
            field=models.CharField(blank=True, choices=[('0%', '0%'), ('20%', '20%'), ('25%', '25%'), ('35%', '35%'), ('45%', '45%'), ('50%', '50%'), ('55%', '55%'), ('60%', '60%')], max_length=10, null=True, verbose_name='No Claim Bonus'),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='previous_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quotationrequest',
            name='add_ons',
            field=models.ManyToManyField(blank=True, to='tickets.addon'),
        ),
        migrations.AlterField(
            model_name='quotationrequest',
            name='preferred_insurer',
            field=models.ManyToManyField(blank=True, to='tickets.insurer'),
        ),
    ]
