# Generated by Django 5.1.6 on 2025-03-04 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_quotationrequest_claim_status_quotationrequest_ncb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationrequest',
            name='business_type',
            field=models.CharField(choices=[('New Business', 'New Business'), ('Renewal', 'Renewal'), ('Rollover', 'Rollover'), ('Break-In', 'Break-In'), ('Used', 'Used')], max_length=50),
        ),
    ]
