# Generated by Django 5.1.6 on 2025-03-04 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_alter_quotationrequest_business_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationrequest',
            name='rto_code',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='RTO Code'),
        ),
    ]
