# Generated by Django 5.1.6 on 2025-03-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_quotationrequest_rto_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationrequest',
            name='registration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
