# Generated by Django 5.1.6 on 2025-03-06 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_alter_quotationrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationrequest',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
