# Generated by Django 5.1.6 on 2025-03-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_quotationrequest_kyc_document1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Assigned', 'Assigned'), ('Resolved', 'Resolved'), ('Incomplete', 'Incomplete'), ('Accepted', 'Accepted'), ('Payment Requested', 'Payment Requested'), ('Changes', 'Changes')], max_length=20),
        ),
        migrations.AlterField(
            model_name='quotationrequest',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Assigned', 'Assigned'), ('Resolved', 'Resolved'), ('Incomplete', 'Incomplete'), ('Accepted', 'Accepted'), ('Payment Requested', 'Payment Requested'), ('Changes', 'Changes')], default='Open', max_length=20),
        ),
    ]
