# Generated by Django 5.1.6 on 2025-03-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0020_alter_activitylog_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Assigned', 'Assigned'), ('Resolved', 'Resolved'), ('Incomplete', 'Incomplete'), ('Accepted', 'Accepted'), ('Payment Requested', 'Payment Requested')], max_length=20),
        ),
        migrations.AlterField(
            model_name='quotationrequest',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Assigned', 'Assigned'), ('Resolved', 'Resolved'), ('Incomplete', 'Incomplete'), ('Accepted', 'Accepted'), ('Payment Requested', 'Payment Requested')], default='Open', max_length=20),
        ),
    ]
