# Generated by Django 5.1.6 on 2025-03-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0024_alter_activitylog_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteattachment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Changes Requested', 'Changes Requested')], default='Pending', max_length=20),
        ),
    ]
