# Generated by Django 5.1.6 on 2025-03-10 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0025_alter_quoteattachment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Assigned', 'Assigned'), ('Resolved', 'Resolved'), ('Incomplete', 'Incomplete'), ('Accepted', 'Accepted'), ('Payment', 'Payment'), ('Changes Requested', 'Changes Requested'), ('Inspection Requested', 'Inspection Requested')], max_length=20),
        ),
        migrations.AlterField(
            model_name='quotationrequest',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Assigned', 'Assigned'), ('Resolved', 'Resolved'), ('Incomplete', 'Incomplete'), ('Accepted', 'Accepted'), ('Payment', 'Payment'), ('Changes Requested', 'Changes Requested'), ('Inspection Requested', 'Inspection Requested')], default='Open', max_length=20),
        ),
        migrations.CreateModel(
            name='InspectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rc_upload', models.FileField(upload_to='inspection_docs/')),
                ('contact_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('quotation_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_requests', to='tickets.quotationrequest')),
            ],
        ),
    ]
