# Generated by Django 5.1.7 on 2025-03-13 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0026_alter_activitylog_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationrequest',
            name='email_id',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
