# Generated by Django 5.1.7 on 2025-03-18 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0028_remove_quotationrequest_comments_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Assigned', 'Assigned'), ('Resolved', 'Resolved'), ('Incomplete', 'Incomplete'), ('Accepted', 'Accepted'), ('Payment', 'Payment'), ('Payment Link Shared', 'Payment Link Shared'), ('Changes Requested', 'Changes Requested'), ('Inspection Requested', 'Inspection Requested')], max_length=20),
        ),
        migrations.AlterField(
            model_name='quotationrequest',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Assigned', 'Assigned'), ('Resolved', 'Resolved'), ('Incomplete', 'Incomplete'), ('Accepted', 'Accepted'), ('Payment', 'Payment'), ('Payment Link Shared', 'Payment Link Shared'), ('Changes Requested', 'Changes Requested'), ('Inspection Requested', 'Inspection Requested')], default='Open', max_length=20),
        ),
    ]
