# Generated by Django 5.1.7 on 2025-03-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0029_alter_activitylog_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationrequest',
            name='document4',
            field=models.FileField(blank=True, upload_to='quotation_docs/'),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='document5',
            field=models.FileField(blank=True, upload_to='quotation_docs/'),
        ),
    ]
