# Generated by Django 5.1.7 on 2025-03-27 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0030_quotationrequest_document4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationrequest',
            name='ncb',
            field=models.CharField(blank=True, choices=[('0%', '0%'), ('20%', '20%'), ('25%', '25%'), ('35%', '35%'), ('45%', '45%'), ('50%', '50%'), ('65%', '65%')], max_length=10, null=True, verbose_name='No Claim Bonus'),
        ),
    ]
